### ISSUE TITLE
Issue Bot

### ISSUE THREAD

**Issue by Tjird** [aubguillemette/discord2slack#2]
https://i.gyazo.com/4060f56b9bacf01cd408ad5ae6a48376.png
I have a error while I'm installing the bot, can you provide some help please?

**Comment by aubguillemette** [comment]
Your screenshot shows you're using node.js v4.2.6 and npm v3.5.2, is it the case? I'm running it on node.js v9.3.0 and npm v5.6.0. I'd suggest trying to update node.js to the lastest version.

**Comment by Tjird** [comment]
Yeah, I'm trying to update now. Which version of Linux do you use?

**Comment by Tjird** [comment]
It's is now working, hero! Butttt it is working from slack to discord but not discord to slack.

**Comment by aubguillemette** [comment]
For the record, I've tested it on Debian 9.3 with node.js v8.9.4 and npm 5.6.0 and OSX 10.13.1 (High Sierra) with node.js v.9.3.0 and npm v5.6.0

Did you make sure to put the Discord channel **id** and not the channel name in the discord2slack.js file?

**Comment by Tjird** [comment]
Yes, every config item is correct. I did recieve the messages in to my server. https://i.gyazo.com/5c1b32d41cbea9fcadf8365c60b3adf0.png
But in slack we don't get a message and in discord we get.

**Comment by Tjird** [comment]
In the mean while, we have tested also Debian but same result...
The message is coming in on the server but not on slack.

**Comment by Tjird** [comment]
I'm here again with an update. Private channels @ slack doens't post messages but public channels do work.

**Comment by aubguillemette** [comment]
Thanks for the update, I found the error. Working on a fix right now.

**Comment by aubguillemette** [comment]
Should work now. There's an additional field in the config to specify whether the channel is private or not. The slackbots package doesn't use the same method to send messages for private and public channels.

I guess there's a better way to do it (there surely must be a way for the code to check if a channel is private or not), I'll keep working on this on my free time.

Thanks a lot for your help! :)
