### ISSUE TITLE
Support for rich messages

### ISSUE THREAD

**Issue by ChipWolf** [aubguillemette/discord2slack#3]
Any planned support for messages containing attachments/rich content?

**Comment by aubguillemette** [comment]
Sorry I haven't had the time to address your issue earlier.

Attachements work both ways:
Discord to Slack --> Slack shows the URL of the uploaded file on Discord's CDN
Slack to Discord --> Discord shows `Full Name (username) <@ID> uploaded a file: ` followed by the URL of the uploaded file on the Slack server.

Sharing rich content _almost_ works: text formatting doesn't quite use the same syntax on Slack and on Discord, so I'd have to write something to parse the text formatting symbols and convert them to the other platform's syntax. I'll try to get on that sometime soon.

**Comment by ChipWolf** [comment]
Awesome, I'll have a look at it if I have time too.
My use case is to forward messages from integrations (non-interactive messages) from Slack to Discord for integrations which don't yet exist for Discord as a temporary measure before I write a native integration.
The JIRA integration for example

**Comment by ChipWolf** [comment]
So, in regards to attachments, I guess it's showing the contents of the fallback parameter
