### ISSUE TITLE
No error if discord channel id not correct

### ISSUE THREAD

**Issue by BHare1985** [aubguillemette/discord2slack#7]
I like the app. It would be nice if you mention what version nodeJs it requires or has been tested with. I installed this on debian and it started with nodejs 0.10 which obviously was too old, but upgrading to nodejs 6 seemed to work although some errors came up.

I dont use discord so I had no idea on how to get the channelId. That could be worth while to include that in the help somewhere because it was a bit involved going into dev mode.

With that said I initially tried the "Server Id" which didnt work but nothing told me that it didnt work. It wasnt until I messaged the bot I saw

```
TypeError: Cannot read property 'send' of undefined
    at /discord2slack/discord2slack.js:96:21
    at Array.forEach (<anonymous>)

```

Then I did investigating and saw `discord_channel = discord_client.channels.findAll("id", DISCORD_CHANNELID)[0];`

I am recommending you do an easy error check to verify the discord channel was found and the correct channel Id was supplied. Otherwise I had no idea why discord -> slack worked but not slack -> discord.

Thanks!

**Comment by aubguillemette** [comment]
Thanks a lot, I will get into this right now.
